# ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# user environment variables
# XDG Base Directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

# editor, viewers and browser
export EDITOR='lvim'
export VISUAL='lvim'
export PAGER='less'
export BROWSER='chromium'

# Wayland fixes
export MOZ_ENABLE_WAYLAND=1
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_TYPE=wayland
export WLR_NO_HARDWARE_CURSORS=1
export WLR_RENDERER_ALLOW_SOFTWARE=1
export _JAVA_AWT_WM_NONREPARENTING=1
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

# java applications
export _JAVA_AWT_NONREPARENTING=1

# FZF settings
export FZF_DEFAULT_OPTS='
    --exact
    --reverse
    --border=rounded
    --cycle
    --height=50%
    --info=hidden
    --color=16
    --color=bg:-1,bg+:#332E41
    --color=fg:#DADAE8,fg+:#DADAE8
    --color=hl:#DADAE8,hl+:#A4B9EF
    --color=prompt:#F2CECF
    --color=pointer:-1
    --color=gutter:-1
    --color=marker:-1
    --color=spinner:-1
    --color=border:#A4B9EF'

# pfetch information 
export PF_INFO="ascii title os kernel uptime pkgs memory editor palette"

# define configuration file location for ripgrep
export RIPGREP_CONFIG_PATH='/home/phbpx/.config/ripgrep/ripgreprc'

# NNN settings
export NNN_FIFO='/tmp/nnn.fifo'
export NNN_TRASH='1' # use trash-cli
export NNN_COLORS='4652' # colors for contexts
export NNN_FCOLORS='0203040a000d0608090b0501' # file specific colors
export NNN_BMS='w:/home/phbpx/Images/backgrounds;p:/home/phbpx/Sources;s:/home/phbpx/Images/screenshots;m:/run/media/phbpx/'
export NNN_PLUG='p:preview-tui;n:nuke'
export NNN_OPTS='deEPrUx'
export NNN_OPENER='/home/phbpx/.config/nnn/plugins/nuke'

# bemenu settings
export BEMENU_OPTS="--fn 'Operator Mono SSm Book' 13px --tb #1E1E28 --tf #A4B9EF --fb #1E1E28 --ff #DADAE8 --nb #1E1E28 --nf #DADAE8 --hb #332E41 --hf #E5B4E2 --sb #332E41 --sf #E5B4E2 -H 32 -M 5px"
