export XDG_CACHE_HOME="$HOME/.cache"

# locale
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"

# wayland fix
export MOZ_ENABLE_WAYLAND=1
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_TYPE=wayland
export WLR_NO_HARDWARE_CURSORS=1
export WLR_RENDERER_ALLOW_SOFTWARE=1
export _JAVA_AWT_WM_NONREPARENTING=1
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

# Default editor
export EDITOR=nvim

# Default browser
export BROWSER=brave

# fzf
export FZF_DEFAULT_COMMAND="rg --files --hidden"
export FZF_CTRL_T_OPTS="--preview '([[ -f {} ]] && (bat --style=numbers --color=always {} || cat {}))'"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS="--layout=reverse --height 96%"

# set a character at the end of partial lines to none.
export PROMPT_EOL_MARK=""

# history settings.
export HISTORY_IGNORE="([bf]g|c|clear|e|exit|h|history|incognito|l|l[adfls]|pwd|z)"

# Obsidian.
export OBSIDIAN_USE_WAYLAND=1

# less
export LESS="--RAW-CONTROL-CHARS"
export LESS_TERMCAP_mb=$'\e[1;31m' # Start blinking
export LESS_TERMCAP_md=$'\e[1;34m' # Start bold mode
export LESS_TERMCAP_me=$'\e[0m' # End all mode
export LESS_TERMCAP_so=$'\e[38;5;215m' # Start standout mode
export LESS_TERMCAP_se=$'\e[0m' # End standout mode
export LESS_TERMCAP_us=$'\e[4;35m' # Start underline
export LESS_TERMCAP_ue=$'\e[0m' # End underline

# Python virtualenv
# disable the default virtualenv prompt change
export VIRTUAL_ENV_DISABLE_PROMPT=1

# Golang
export GOPATH=$HOME/.local/share/go
export PATH=$PATH:$HOME/.local/share/go/bin

# Path
export PATH=$PATH:$HOME/.local/bin

# Electron
export ELECTRON_TRASH=trash-cli
