export ZSH="$HOME/.oh-my-zsh"

### Theme
ZSH_THEME="robbyrussell"

### Plugins
plugins=(
	asdf
  docker-compose
	extract
	F-Sy-H
  fzf
	z
  zsh-sdkman
)

### oh-my-zsh
source $ZSH/oh-my-zsh.sh

### User configuration

# direnv
eval "$(direnv hook zsh)"

# Golang
export GOPATH=$HOME/.local/share/go
export PATH=$PATH:$HOME/.local/share/go/bin

# krew
export PATH="${PATH}:${HOME}/.krew/bin"

# Aliases
alias zshconfig="$EDITOR ~/.zshrc"
alias sourcezsh="source $HOME/.zshrc"
alias vim="nvim"
alias ssh="kitty +kitten ssh"
alias ls="lsd"
alias rm="rmtrash"
alias grep="rg"
alias c='clear'
alias e='exit'
alias ip-address='curl -s -H "Accept: application/json" https://ipinfo.io/json | jq "del(.loc, .postal, .readme)"'

### Functions

# Super mkdir
mkd() {
    mkdir -pv "$@"
    cd "$@"
}

# Weather
wttr() {
    curl -s "https://wttr.in/${1:-Valinhos}?m2F&format=v2"
}

# INIT Starship
eval "$(starship init zsh)"
