export ZSH="$HOME/.oh-my-zsh"

### Theme
ZSH_THEME="robbyrussell"

### Plugins
plugins=(
  asdf
  extract
  fzf
  podman
  z
  zsh-syntax-highlighting
)

### oh-my-zsh
source $ZSH/oh-my-zsh.sh

### User configuration

# Aliases
alias zshconfig="$EDITOR ~/.zshrc"
alias sourcezsh="source $HOME/.zshrc"
alias vim="nvim"
alias ls="lsd"
alias rm="rmtrash"
alias grep="rg"
alias c='clear'
alias e='exit'
alias ip-address='curl -s -H "Accept: application/json" https://ipinfo.io/json | jq "del(.loc, .postal, .readme)"'

### Functions

# Super mkdir
mkd() {
  mkdir -pv "$@"
  cd "$@"
}
