theme = "native"

[[block]]
block = "networkmanager"
on_click = "nm-connection-editor"
interface_name_exclude = ['br\-[0-9a-f]{12}', 'docker\d+']
interface_name_include = []
ap_format = "{ssid^10} ({strength})"
device_format = "{typename} {ap}"
[block.theme_overrides]
good_fg = "#22CC00"

[[block]]
block = "cpu"
interval = 1
format = "{utilization} {frequency}"
[block.theme_overrides]
warning_bg = "#0088cc"
warning_fg = "#ffffff"
critical_bg = "#900000"
critical_fg = "#ffffff"

[[block]]
block = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95
[block.theme_overrides]
warning_bg = "#0088cc"
warning_fg = "#ffffff"
critical_bg = "#900000"
critical_fg = "#ffffff"

[[block]]
block = "sound"
format = "{volume}"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"
full_format = "{percentage}"
[block.theme_overrides]
warning_bg = "#0088cc"
warning_fg = "#ffffff"
critical_bg = "#900000"
critical_fg = "#ffffff"

[[block]]
block = "time"
interval = 5
format = "%R"
