theme = "native"

[[block]]
block = "pomodoro"
length = 25
break_length = 5
message = "Take a break!"
break_message = "Back to work!"
notifier = "swaynag"

[[block]]
block = "toggle"
text = "VPN"
command_state = "~/.local/bin/vpn.sh status"
command_on = "~/.local/bin/vpn.sh toggle"
command_off = "~/.local/bin/vpn.sh toggle"
interval = 5

[[block]]
block = "net"
device = "wlan0"
format = "{signal_strength} at {ssid} [{ip}]"
hide_inactive = true
interval = 5
[block.theme_overrides]
idle_fg = "#22CC00"

[[block]]
block = "net"
device = "enp0s31f6"
format = ""
hide_inactive = true
interval = 5
[block.theme_overrides]
idle_fg = "#22CC00"

[[block]]
block = "load"
interval = 1

[[block]]
block = "sound"
format = "{volume}"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"
full_format = "{percentage}"
[block.theme_overrides]
warning_bg = "#0088cc"
warning_fg = "#ffffff"
critical_bg = "#900000"
critical_fg = "#ffffff"

[[block]]
block = "time"
interval = 5
format = "%R"
